name: client_android_modelviewlabsorg_desafio_api
description: "Client android do aplicativo gerado no Desafio para processo seletivo ModelViewLabsOrg - Desenvolvedor"

publish_to: 'none' 
version: 0.1.0
homepage: https://github.com/pwlimaverde/modelviewlabsorg-desafio-api
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  #Dependencias internas
  dependencies:
    path: ../../modules/dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: IconsPadrao
      fonts:
        - asset: assets/fonts/IconsPadrao.ttf
