name: client_web_modelviewlabsorg_desafio_api
description: "Client web do aplicativo gerado no Desafio para processo seletivo ModelViewLabsOrg - Desenvolvedor"
publish_to: 'none' 
version: 0.0.4
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  dependencies:
    path: ../../modules/dependencies
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: IconsPadrao
      fonts:
        - asset: assets/fonts/IconsPadrao.ttf
